/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "InAppReceiptModule"
 * 	found in "InAppReceipt.asn1"
 */

#ifndef	_InAppReceipt_H_
#define	_InAppReceipt_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SET_OF.h>
#include <constr_SET_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct InAppAttribute;

/* InAppReceipt */
typedef struct InAppReceipt {
	A_SET_OF(struct InAppAttribute) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InAppReceipt_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InAppReceipt;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "InAppAttribute.h"

#endif	/* _InAppReceipt_H_ */
#include <asn_internal.h>
