/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "InAppReceiptModule"
 * 	found in "InAppReceipt.asn1"
 */

#ifndef	_InAppAttribute_H_
#define	_InAppAttribute_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* InAppAttribute */
typedef struct InAppAttribute {
	long	 type;
	long	 version;
	OCTET_STRING_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InAppAttribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InAppAttribute;

#ifdef __cplusplus
}
#endif

#endif	/* _InAppAttribute_H_ */
#include <asn_internal.h>
