/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "ReceiptModule"
 * 	found in "AppReceipt.asn1"
 */

#ifndef	_ReceiptAttribute_H_
#define	_ReceiptAttribute_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReceiptAttribute */
typedef struct ReceiptAttribute {
	long	 type;
	long	 version;
	OCTET_STRING_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReceiptAttribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReceiptAttribute;

#ifdef __cplusplus
}
#endif

#endif	/* _ReceiptAttribute_H_ */
#include <asn_internal.h>
